# .coderabbit.yml
project:
  name: "Restaurant-OS"
  description: "Laravel 11 + Livewire v3 + Tailwind restaurant management system"

rules:
  - "Use ULID primary keys for all models"
  - "All money fields must be decimal(12,2) — never float"
  - "Controllers must call $this->authorize() for protected actions"
  - "Never expose .env or credentials"
  - "No raw hex colors; use Tailwind tokens or design-system variables"
  - "Each page must support Light/Dark themes and translations (EN/AM/TI)"
  - "Each PR must include at least one Pest feature test for new logic"
  - "Respect MVC boundaries — no direct queries inside Blade views"
  - "Run composer lint and npm run build before merging"

review:
  mode: "pull_request"
  depth: "full"
  languages:
    - php
    - blade
    - javascript
  framework: laravel
  severity:
    security: high
    performance: high
    readability: medium
    maintainability: medium
  output: "github_pr_comments"

style:
  prefer_psr12: true
  naming_conventions: "snake_case for DB, camelCase for PHP, kebab-case for Blade components"

tests:
  required: true
  framework: pest
