import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css', 
                'resources/js/app.js',
                'resources/css/admin/layout.css',
                'resources/js/admin/layout.js',
                'resources/css/admin/modal-fix.css',
                'resources/js/admin/modal-system.js',
                'resources/css/admin/staff.css',
                'resources/js/admin/staff.js',
                'resources/css/admin/staff-performance.css',
                'resources/js/admin/staff-performance.js',
                'resources/css/admin/staff-attendance.css',
                'resources/js/admin/staff-attendance.js',
            'resources/css/admin/inventory-stock-levels.css',
            'resources/js/admin/inventory-stock-levels.js',
            'resources/css/admin/inventory-ingredients.css',
            'resources/js/admin/inventory-ingredients.js',
            'resources/css/admin/inventory-settings.css',
            'resources/js/admin/inventory-settings.js',
            'resources/css/admin/inventory-recipes.css',
            'resources/js/admin/inventory-recipes.js',
            'resources/css/admin/inventory-movements.css',
            'resources/js/admin/inventory-movements.js',
            'resources/css/admin/inventory-purchasing.css',
            'resources/js/admin/inventory-purchasing.js',
            'resources/css/admin/inventory-locations.css',
            'resources/js/admin/inventory-locations.js',
            'resources/css/admin/injera/flour-management.css',
            'resources/js/admin/injera/flour-management.js',
            'resources/css/admin/injera/bucket-configurations.css',
            'resources/js/admin/injera/bucket-configurations.js',
            'resources/css/admin/injera/production-batches.css',
            'resources/js/admin/injera/production-batches.js',
            'resources/css/admin/injera/injera-stock-levels.css',
            'resources/js/admin/injera/injera-stock-levels.js',
            'resources/css/admin/injera/cost-analysis.css',
            'resources/js/admin/injera/cost-analysis.js',
            'resources/css/admin/injera/orders.css',
            'resources/js/admin/injera/orders.js',
            'resources/css/admin/geez-logo-animations.css',
            'resources/js/admin/geez-logo-animations.js',
                'resources/css/admin/todos/overview.css',
                'resources/js/admin/todos/overview.js',
                'resources/css/admin/todos/staff-lists.css',
                'resources/js/admin/todos/staff-lists.js',
                'resources/css/admin/todos/templates.css',
                'resources/js/admin/todos/templates.js',
                'resources/css/admin/todos/schedules.css',
                'resources/js/admin/todos/schedules.js',
                'resources/css/admin/todos/progress.css',
                'resources/js/admin/todos/progress.js',
                'resources/css/admin/activities/manage.css',
                'resources/js/admin/activities/manage.js',
                'resources/css/admin/activities/logging.css',
                'resources/js/admin/activities/logging.js',
                'resources/css/admin/activities/analytics.css',
                'resources/js/admin/activities/analytics.js',
                'resources/css/admin/activities/assignments.css',
                'resources/js/admin/activities/assignments.js',
                'resources/css/admin/shifts/overview.css',
                'resources/js/admin/shifts/overview.js',
                'resources/css/admin/shifts/manage.css',
                'resources/js/admin/shifts/manage.js',
                'resources/css/admin/shifts/assignments.css',
                'resources/js/admin/shifts/assignments.js',
                'resources/css/admin/shifts/templates.css',
                'resources/js/admin/shifts/templates.js',
                // Tables section
                'resources/css/admin/tables/table-types.css',
                'resources/js/admin/tables/table-types.js',
                'resources/css/admin/tables/table-categories.css',
                'resources/js/admin/tables/table-categories.js',
                'resources/css/admin/tables/table-layout.css',
                'resources/js/admin/tables/table-layout.js',
                'resources/css/admin/tables/rooms-management.css',
                'resources/js/admin/tables/rooms-management.js',
                // Reports section
                'resources/css/admin/reports/executive-reports.css',
                'resources/js/admin/reports/executive-reports.js',
                'resources/css/admin/reports/financial-reports.css',
                'resources/js/admin/reports/financial-reports.js',
                'resources/css/admin/reports/operational-reports.css',
                'resources/js/admin/reports/operational-reports.js',
                'resources/css/admin/reports/staff-reports.css',
                'resources/js/admin/reports/staff-reports.js',
                'resources/css/admin/reports/inventory-reports.css',
                'resources/js/admin/reports/inventory-reports.js',
                'resources/css/admin/reports/menu-reports.css',
                'resources/js/admin/reports/menu-reports.js',
                'resources/css/admin/reports/sales-reports.css',
                'resources/js/admin/reports/sales-reports.js',
                'resources/css/admin/reports/customer-reports.css',
                'resources/js/admin/reports/customer-reports.js',
                // Bar section
                'resources/css/admin/bar/settings.css',
                'resources/js/admin/bar/settings.js',
                'resources/css/admin/bar/suppliers.css',
                'resources/js/admin/bar/suppliers.js',
                'resources/css/admin/bar/analytics.css',
                'resources/js/admin/bar/analytics.js',
                'resources/css/admin/bar/pricing.css',
                'resources/js/admin/bar/pricing.js',
                'resources/css/admin/bar/cocktail-recipes.css',
                'resources/js/admin/bar/cocktail-recipes.js',
                'resources/css/admin/bar-inventory.css',
                'resources/js/admin/bar-inventory.js',
                // Settings and other sections
                'resources/css/admin/restaurant-settings.css',
                'resources/js/admin/restaurant-settings.js',
                'resources/css/admin/expenses.css',
                'resources/js/admin/expenses.js',
                'resources/css/admin/customer-feedback.css',
                'resources/js/admin/customer-feedback.js',
                'resources/css/admin/customer-analytics.css',
                'resources/js/admin/customer-analytics.js',
                'resources/css/admin/customer-reservations.css',
                'resources/js/admin/customer-reservations.js',
                'resources/css/admin/customer-loyalty.css',
                'resources/js/admin/customer-loyalty.js',
                'resources/css/admin/customer-directory.css',
                'resources/js/admin/customer-directory.js',
                // Menu section
                'resources/css/admin/menu-design.css',
                'resources/js/admin/menu-design.js',
                'resources/css/admin/menu-pricing.css',
                'resources/js/admin/menu-pricing.js',
                'resources/css/admin/menu-dish-cost.css',
                'resources/js/admin/menu-dish-cost.js',
                'resources/css/admin/menu-modifiers.css',
                'resources/js/admin/menu-modifiers.js',
                'resources/css/admin/menu-categories.css',
                'resources/js/admin/menu-categories.js',
                'resources/css/admin/food-items.css',
                'resources/js/admin/food-items.js',
                // Finance section
                'resources/css/admin/finance-settings.css',
                'resources/js/admin/finance-settings.js',
                'resources/css/admin/financial-reports.css',
                'resources/js/admin/financial-reports.js',
                'resources/css/admin/budgeting.css',
                'resources/js/admin/budgeting.js',
                // Sales section
                'resources/css/admin/sales.css',
                'resources/js/admin/sales.js',
                // Inventory additional
                'resources/css/admin/inventory-stocktakes.css',
                'resources/js/admin/inventory-stocktakes.js',
                'resources/css/admin/inventory-analytics.css',
                'resources/js/admin/inventory-analytics.js',
                'resources/css/admin/inventory-alerts.css',
                'resources/js/admin/inventory-alerts.js',
                'resources/css/admin/inventory-suppliers.css',
                'resources/js/admin/inventory-suppliers.js',
                // Injera management
                'resources/css/admin/injera/management.css',
                'resources/js/admin/injera/management.js',
                // Staff additional
                'resources/css/admin/staff-payroll.css',
                'resources/js/admin/staff-payroll.js'
            ],
            refresh: true,
        }),
    ],
});
