import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css', 
                'resources/js/app.js',
                'resources/css/admin/layout.css',
                'resources/js/admin/layout.js',
                'resources/css/admin/staff.css',
                'resources/js/admin/staff.js',
                'resources/css/admin/staff-performance.css',
                'resources/js/admin/staff-performance.js',
                'resources/css/admin/staff-attendance.css',
                'resources/js/admin/staff-attendance.js',
            'resources/css/admin/inventory-stock-levels.css',
            'resources/js/admin/inventory-stock-levels.js',
            'resources/css/admin/inventory-ingredients.css',
            'resources/js/admin/inventory-ingredients.js',
            'resources/css/admin/inventory-settings.css',
            'resources/js/admin/inventory-settings.js',
            'resources/css/admin/inventory-recipes.css',
            'resources/js/admin/inventory-recipes.js',
            'resources/css/admin/inventory-movements.css',
            'resources/js/admin/inventory-movements.js',
            'resources/css/admin/inventory-purchasing.css',
            'resources/js/admin/inventory-purchasing.js',
            'resources/css/admin/inventory-locations.css',
            'resources/js/admin/inventory-locations.js',
            'resources/css/admin/injera/flour-management.css',
            'resources/js/admin/injera/flour-management.js',
            'resources/css/admin/injera/bucket-configurations.css',
            'resources/js/admin/injera/bucket-configurations.js',
            'resources/css/admin/injera/production-batches.css',
            'resources/js/admin/injera/production-batches.js',
            'resources/css/admin/injera/injera-stock-levels.css',
            'resources/js/admin/injera/injera-stock-levels.js',
            'resources/css/admin/injera/cost-analysis.css',
            'resources/js/admin/injera/cost-analysis.js',
            'resources/css/admin/injera/orders.css',
            'resources/js/admin/injera/orders.js',
            'resources/css/admin/geez-logo-animations.css',
            'resources/js/admin/geez-logo-animations.js',
                'resources/css/admin/todos/overview.css',
                'resources/js/admin/todos/overview.js',
                'resources/css/admin/todos/staff-lists.css',
                'resources/js/admin/todos/staff-lists.js',
                'resources/css/admin/todos/templates.css',
                'resources/js/admin/todos/templates.js',
                'resources/css/admin/todos/schedules.css',
                'resources/js/admin/todos/schedules.js',
                'resources/css/admin/todos/progress.css',
                'resources/js/admin/todos/progress.js',
                'resources/css/admin/activities/manage.css',
                'resources/js/admin/activities/manage.js',
                'resources/css/admin/activities/logging.css',
                'resources/js/admin/activities/logging.js',
                'resources/css/admin/activities/analytics.css',
                'resources/js/admin/activities/analytics.js',
                'resources/css/admin/activities/assignments.css',
                'resources/js/admin/activities/assignments.js',
                'resources/css/admin/shifts/overview.css',
                'resources/js/admin/shifts/overview.js',
                'resources/css/admin/shifts/manage.css',
                'resources/js/admin/shifts/manage.js',
                'resources/css/admin/shifts/assignments.css',
                'resources/js/admin/shifts/assignments.js',
                'resources/css/admin/shifts/templates.css',
                'resources/js/admin/shifts/templates.js'
            ],
            refresh: true,
        }),
    ],
});
